name: Workflow to create Jira change upon release
run-name: "Release"
on:
  workflow_dispatch:
  release:
    types: published

jobs:
  check-if-tag-is-correct:
    runs-on: ubuntu-latest
    steps:
      - name: check tag
        run: |
          echo ${{ github.ref }}
      


