name: Print Value in Job Summary and Outputs

on:
  workflow_dispatch

jobs:
  generate_value:
    runs-on: ubuntu-latest
    outputs:
      my_value: ${{ steps.store_value.outputs.value }}
    steps:
      - name: Generate Value
        id: store_value
        run: echo "value=Generated Output Value" >> $GITHUB_OUTPUT

      - name: Print to Job Summary
        run: |
          echo "### 🔥 Important Output 🔥" >> $GITHUB_STEP_SUMMARY
          echo "**Value:** ${{ steps.store_value.outputs.value }}" >> $GITHUB_STEP_SUMMARY

  use_value:
    runs-on: ubuntu-latest
    needs: generate_value
    steps:
      - name: Print Output from Previous Job
        run: echo "The value is: ${{ needs.generate_value.outputs.my_value }}"
