name: Triggered by Repo 1 Release

on:
  repository_dispatch:
    types: [release-published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Deployment
        run: |
          echo "Triggered by Repo 1 release."
          echo "Release Tag: ${{ github.event.client_payload.release_tag }}"
          echo "Release Name: ${{ github.event.client_payload.release_name }}"
          echo "Release Description: ${{ github.event.client_payload.release_description }}"
          echo "Release pre-release: ${{ github.event.client_payload.prerelease }}"
