name: Jira Trigger Workflow

on:
  repository_dispatch:
    types:
      - jira-event # Match the event type from Jira

jobs:
  process-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Read Payload from Repository Dispatch
        env:
          ISSUE_KEY: ${{ github.event.client_payload.issue_key }}
          STATUS: ${{ github.event.client_payload.status }}
          SUMMARY: ${{ github.event.client_payload.summary }}
        run: |
          echo "Jira Issue Key: $ISSUE_KEY"
          echo "Issue Status: $STATUS"
          echo "Issue Summary: $SUMMARY"
