name: Print Release Details

on:
  workflow_call:
    inputs: &common_inputs
      ENVIRONMENT:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      QOS_FILE_NAME:
        required: true
        type: string

  workflow_dispatch:
    inputs: *common_inputs

jobs:
  print-release-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Tag
        run: echo "Release Tag"
