name: Print Inputs Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person'
        required: true
        
      home:
        description: 'Home location'
        required: true
        

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print the name input
        run: |
          echo "Name: ${{ github.event.inputs.name }}"

      - name: Print the home input
        run: |
          echo "Home: ${{ github.event.inputs.home }}"
