name: Process Release Tag

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The release tag passed from another workflow'
        required: true

jobs:
  process-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print the release tag
        run: |
          echo "Received Release Tag: ${{ github.event.inputs.release_tag }}"

      - name: Create a JIRA ticket
        run: |
          python -m pip install --upgrade pip
          output=$(python python_files/noti-service.py --tag ${{ github.event.inputs.release_tag }} --summary ${{ github.event.inputs.release_tag }})
          echo "Script output: $output"
          echo "::set-output name=json::$output"

       

          
   
  
