name: Print Release Details

on:
  release:
    types: [published]

jobs:
  print-release-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Tag
        run: echo "Release Tag: ${{ github.event.release.tag_name }}"
      
      - name: Print Pre-release Status
        run: echo "Is Pre-release: ${{ github.event.release.prerelease }}"
      
      - name: Print Release Notes
        run: echo "Release Notes: ${{ github.event.release.body }}"
       - name: Print Release Notes
        run: echo "Release Notes: ${{ github.event.release.author.login }}"
