name: Workflow to create Jira change upon release
run-name: "Release"
on:
  workflow_dispatch:
  release:
    types: published

jobs:
  check-if-tag-is-correct:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Tag
        run: |
          if [[ ! "$TAG_NAME" =~ ^scoring-service@[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid tag format: $TAG_NAME"
            echo "Tag must follow the convention: scoring-service@X.X.X.X (e.g., scoring-service@1.2.3.4)"
          fi
          echo "✅ Valid tag format: $TAG_NAME"
      - name: Print Release Tag
        run: |
          id_value = "2"
          echo $id_value
          echo "Release_tag:$id_value" >> $GITHUB_STEP_SUMMARY


