name: Print Inputs Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'release_tag'
        required: true

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print the name input
        run: |
          echo "TAG: ${{ github.event.inputs.name }}"


