name: Triggered by Jira Webhook

on:
  repository_dispatch:
    types:
      - jira-event

jobs:
  process-jira-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print Jira Payload
        run: echo "Received Jira event: ${{ github.event.client_payload }}"

      - name: Check Issue Details
        run: |
          echo "Issue key: ${{ github.event.client_payload.issue_key }}"
          echo "Issue status: ${{ github.event.client_payload.status }}"
