name: Postman Trigger Workflow

on:
  repository_dispatch:
    types:
      - on-demand-test # Matches the event_type from the API payload

jobs:
  process-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Process Client Payload
        env:
          UNIT_TEST: ${{ github.event.client_payload.unit }}
          INTEGRATION_TEST: ${{ github.event.client_payload.integration }}
        run: |
          echo "Unit Test Triggered: $UNIT_TEST"
          echo "Integration Test Triggered: $INTEGRATION_TEST"

      - name: Run Unit Tests (Conditional)
        if: env.UNIT_TEST == 'true'
        run: |
          echo "Running Unit Tests..."

      - name: Run Integration Tests (Conditional)
        if: env.INTEGRATION_TEST == 'true'
        run: |
          echo "Running Integration Tests..."
