name: Process Release Tag

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The release tag passed from another workflow'
        required: true
      release_title:
        description: 'The release title passed from another workflow'
        required: true

jobs:
  process-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print the release tag
        run: |
          echo "Received Release Tag: ${{ github.event.inputs.release_tag }}"

      - name: Create a JIRA payload
        run: |
          python -m pip install --upgrade pip
          output=$(python python_files/noti.py --tag ${{ github.event.inputs.release_tag }} --summary ${{ github.event.inputs.release_title }})
          echo "Script output: $output"
          echo "::set-output name=json::$output"
          pyhton python_files/create_jira_ticket.py --payload_data $output --jira_user ${{secrets.jira_user}} --jira_key ${{secrets.jira_key}}


          

          

       

          
   
  
