name: on-demand-test

on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types:
      - postman-event

jobs:
  process-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Read Payload from Repository Dispatch
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Execute Python script
        run: python python_files/create_jira_ticket.py
